-- Hardly Knower
local _M = {}

local _support_tbl = {}

local _header = {
    '# Support',
    '',
    '*This file is automatically generated by lua/supporter.lua.*',
    '',
    'The following are tables that show the supported funcitons',
}

-- _M.tbl_init({
--     { name, title, {
--         "",
--         "",
--     } }
-- })

_M.init = function(tbls)
    if type(tbls) ~= 'table' then
        -- TODO: add
        vim.notify('Supporter improper data format in tbls')
        return
    end

    for _, tbl in ipairs(tbls) do
        if type(tbl) ~= 'list' and type(tbl) ~= 'table' then
            -- TODO: add
            vim.notify('Supporter improper data format in tbl: '.. vim.inspect(tbl))
            return
        end
        local name = tbl[1]
        local title = tbl[2]
        local by = tbl[3]
        local desc_tbl = tbl[4]

        if type(name) ~= 'string' then
            -- TODO: add
            vim.notify('Supporter improper data format in name')
            return
        elseif type(title) ~= 'string' then
            -- TODO: add
            vim.notify('Supporter improper data format in title')
            return
        elseif type(by) ~= 'list' and type(by) ~= 'table' then
            -- TODO: add
            vim.notify('Supporter improper dat{} at in by')
            return
        elseif type(desc_tbl) ~= 'list' and type(desc_tbl) ~= 'table' then
            -- TODO: add
            vim.notify('Supporter improper data format in desc_tbl: ' .. type(desc_tbl))
            return
        end

        _support_tbl[name] = {
            { name, title, by, desc_tbl }
        }
    end
end

-- insert('plugins', {
--     { index, by }
-- })
_M.insert = function (name, indicies_by)
    if type(name) ~= 'string' then
        -- TODO: add
        vim.notify('Supporter improper insert format in name')
        return
    elseif type(indicies_by) ~= 'list' and type(indicies_by) ~= 'table' then
        -- TODO: add
        vim.notify('Supporter improper insert format in indicies_by: ' .. name)
        return
    end

    if _support_tbl[name] == nil then
        -- TODO: add
        vim.notify('Supporter improper insert Table uninitialized: ' .. name)
        return
    end


    for _, index_by in ipairs(indicies_by) do
        if type(index_by[1]) ~= 'string' then
            -- TODO: add
            vim.notify('Supporter improper insert format in index_by[1]')
            return
        elseif type(index_by[2]) ~= 'list' and type(index_by[2]) ~= 'table' then
            -- TODO: add
            vim.notify('Supporter improper insert format in index_by[2]: ' .. type(index_by[2]))
            return
        end

        table.insert(_support_tbl[name], index_by)
    end
end


_M.is = function (name)
    if type(name) ~= 'string' then
        -- TODO: add
        vim.notify('Supporter.in improper by format in name')
        return
    end

    if _support_tbl[name] == nil then
        -- TODO: add
        vim.notify('Supporter.in improper by Table uninitialized')
        return
    end


    local out_list = {}
    for i, by_tbl in ipairs(_support_tbl[name]) do
        if i ~= 1 then
            table.insert(out_list, by_tbl[1])
        end
    end
    return out_list
end

_M.by = function (name)
    if type(name) ~= 'string' then
        -- TODO: add
        vim.notify('Supporter improper by format in name')
        return
    end

    if _support_tbl[name] == nil then
        -- TODO: add
        vim.notify('Supporter improper by Table uninitialized')
        return
    end

    local unique_list = {}

    -- local unique_list = {
    --     ['test1'] = true,
    --     ['test2'] = true,
    -- }

    for i, by_tbl in ipairs(_support_tbl[name]) do
        if i ~= 1 then
            if type(by_tbl) ~= 'list' and type(by_tbl) ~= 'table' then
                vim.notify('Failed to validate by_tbl ' .. type(by_tbl) .. ': ' .. vim.inspect(by_tbl))
                return
            end
            if type(by_tbl[2]) ~= 'list' and type(by_tbl[2]) ~= 'table' then
                vim.notify('Failed to validate by_tbl[2] ' .. type(by_tbl[2]) .. ': ' .. vim.inspect(by_tbl[2]))
                return
            end
            for _, index in ipairs(by_tbl[2]) do
                unique_list[index] = true
            end
        end
    end

    local out_list = {}
    for name, bool in pairs(unique_list) do
        table.insert(out_list, name)
    end
    return out_list
end


_M.gen = function ()
    local config_path = vim.fn.stdpath('config')..'/docs'
    local filename = 'Support.md'
    local full_path = config_path..'/'..filename

    local file = io.open(full_path, 'w')
    if not file then
        vim.notify("Failed to write file to " .. full_path, vim.log.levels.ERROR)
        return
    end
    for _, str in ipairs(_header) do
        file:write(str..'\n')
    end
    file:close()
end


_M.return_table = function ()
    return _support_tbl
end

return _M
