-- Hardly Knower
local _M = {}

local _support_tbl = {}

local _header = {
    '# Support',
    '',
    '*This file is automatically generated by lua/supporter.lua.*',
    '',
    'The following are tables that show the supported funcitons',
}

-- _M.tbl_init({
--     { name, title, {
--         "",
--         "",
--     } }
-- })

_M.init = function(tbls)
    if not type(tbls) == 'table' then
        -- TODO: add
        vim.notify('Supporter improper data format in tbls')
        return
    end

    for _, tbl in ipairs(tbls) do
        if type(tbl) == 'list' then
            -- TODO: add
            vim.notify('Supporter improper data format in tbl')
            return
        end
        local name = tbl[1]
        local title = tbl[2]
        local by = tbl[3]
        local desc_tbl = tbl[4]

        if not type(name) == 'string' then
            -- TODO: add
            vim.notify('Supporter improper data format in name')
            return
        elseif not type(title) == 'string' then
            -- TODO: add
            vim.notify('Supporter improper data format in title')
            return
        elseif not type(by) == 'list' then
            -- TODO: add
            vim.notify('Supporter improper data format in by')
            return
        elseif not type(desc_tbl) == 'list' then
            -- TODO: add
            vim.notify('Supporter improper data format in desc_tbl')
            return
        end

        _support_tbl[name] = {
            { name, title, by, desc_tbl }
        }
    end
end

-- insert('plugins', {
--     { index, by }
-- })
_M.insert = function (name, indicies_by)
    if not type(name) == 'string' then
        -- TODO: add
        vim.notify('Supporter improper insert format in name')
        return
    elseif not type(indicies_by) == 'list' then
        -- TODO: add
        vim.notify('Supporter improper insert format in indicies_by')
    end


    for _, index_by in ipairs(indicies_by) do
        if not type(index_by[1]) == 'string' then
            -- TODO: add
            vim.notify('Supporter improper insert format in index_by[1]')
            return
        elseif not type(index_by[2]) == 'list' then
            -- TODO: add
            vim.notify('Supporter improper insert format in index_by[2]')
            return
        end

        if not _support_tbl[name] == nil then
            -- TODO: add
            vim.notify('Supporter improper insert Table uninitialized')
            return
        end
        table.insert(_support_tbl[name], index_by)
    end
end

_M.gen = function ()
    local config_path = vim.fn.stdpath('config')..'/docs'
    local filename = 'Support.md'
    local full_path = config_path..'/'..filename

    local file = io.open(full_path, 'w')
    if not file then
        vim.notify("Failed to write file to " .. full_path, vim.log.levels.ERROR)
        return
    end
    for _, str in ipairs(_header) do
        file:write(str..'\n')
    end
    file:close()
end

_M.return_table = function ()
    return _support_tbl
end

return _M
